services:
  profilarr:
      image: python:3.12-slim-bullseye  # Replace with the actual image for Profilarr
      container_name: profilarr
      command: >
            bash -c "
            apt-get update &&
            apt-get -y install git &&
            mkdir /app &&
            cd /app &&
            git clone https://github.com/ric866/Profilarr.git /app &&
            pip install -r /app/requirements.txt &&
            python setup.py &&
            tail -f /dev/null"   
      environment:
        - MASTER_RADARR_BASEURL :"http://localhost:7878" #replace with your actual servername
        - MASTER_RADARR_APIKEY :"ABCEasdffgsrtye54y45y54" #replace with your actual API Key
        - MASTER_SONARR_BASEURL :"http://localhost:7878" #replace with your actual servername
        - MASTER_SONARR_APIKEY :"ABCEasdffgsrtye54y45y54" #replace with your actual API Key
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
      volumes:
        - profilarr_config:/config
      restart: no
      stdin_open: true 
      tty: true
volumes:
  profilarr_config:
  
